FROM python:3.11-alpine

ENV PYTHONUNBUFFERED=1

WORKDIR /

RUN pip install python-dotenv
RUN apk update && apk --no-cache add mariadb-dev build-base pkgconfig

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["python","manage.py","runserver","0.0.0.0:8000"]