# Generated by Django 4.2.7 on 2023-11-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idPersona', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nac', models.DateField()),
                ('foto', models.ImageField(upload_to='fotos')),
                ('celular', models.IntegerField()),
            ],
        ),
    ]
